# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
     my_action_job:
            runs-on: windows-latest
            name: A job to run VSTest
            steps:
             - name: Download vstest.console.exe
               run: |
                  Invoke-WebRequest -Uri https://aka.ms/vstest16 -OutFile vstest.zip
                  Expand-Archive -Path vstest.zip -DestinationPath "$env:ProgramFiles(x86)\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\TestPlatform"
                  Remove-Item vstest.zip

             - name: Run Tests
               run: $env:ProgramFiles(x86)\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\TestPlatform\vstest.console.exe platform\Autofox.Transport.Platform.CoreTests\bin\Release\Autofox.Transport.Platform.CoreTests.dll
